name: Unit Tests

on:
  pull_request:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
    test-php:
      runs-on: ubuntu-latest
      strategy:
          fail-fast: true
          matrix:
              php:
                - '7.4'
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@e6f75134d35752277f093989e72e140eaa222f35 # v2.28.0
        with:
              php-version: '${{ matrix.php }}'
              coverage: none
      - name: Install
        run: |
          npm install
          composer install
      - name: Test
        run: npm test